# Generated by Django 4.0.6 on 2022-08-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_images_image4_stores_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='comment',
            new_name='admin_comment',
        ),
    ]
