# Generated by Django 4.0.6 on 2022-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_rename_comment_stores_admin_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
